// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mayachain/v1/x/mayachain/types/msg_refund.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	gitlab_com_mayachain_mayanode_common "gitlab.com/mayachain/mayanode/common"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgRefundTx struct {
	Tx     ObservedTx                                    `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx"`
	InTxID gitlab_com_mayachain_mayanode_common.TxID     `protobuf:"bytes,2,opt,name=in_tx_id,json=inTxId,proto3,casttype=gitlab.com/mayachain/mayanode/common.TxID" json:"in_tx_id,omitempty"`
	Signer github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,3,opt,name=signer,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"signer,omitempty"`
}

func (m *MsgRefundTx) Reset()         { *m = MsgRefundTx{} }
func (m *MsgRefundTx) String() string { return proto.CompactTextString(m) }
func (*MsgRefundTx) ProtoMessage()    {}
func (*MsgRefundTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9115af5c4ef9e45, []int{0}
}
func (m *MsgRefundTx) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRefundTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRefundTx.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRefundTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRefundTx.Merge(m, src)
}
func (m *MsgRefundTx) XXX_Size() int {
	return m.Size()
}
func (m *MsgRefundTx) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRefundTx.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRefundTx proto.InternalMessageInfo

func (m *MsgRefundTx) GetTx() ObservedTx {
	if m != nil {
		return m.Tx
	}
	return ObservedTx{}
}

func (m *MsgRefundTx) GetInTxID() gitlab_com_mayachain_mayanode_common.TxID {
	if m != nil {
		return m.InTxID
	}
	return ""
}

func (m *MsgRefundTx) GetSigner() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.Signer
	}
	return nil
}

func init() {
	proto.RegisterType((*MsgRefundTx)(nil), "types.MsgRefundTx")
}

func init() {
	proto.RegisterFile("mayachain/v1/x/mayachain/types/msg_refund.proto", fileDescriptor_e9115af5c4ef9e45)
}

var fileDescriptor_e9115af5c4ef9e45 = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xbd, 0x4e, 0xeb, 0x30,
	0x1c, 0xc5, 0xe3, 0xde, 0x4b, 0x04, 0x29, 0x0b, 0x11, 0x43, 0xd5, 0x21, 0xa9, 0x58, 0x28, 0x43,
	0x6d, 0x15, 0x84, 0x98, 0x1b, 0xb1, 0x64, 0x40, 0x88, 0xa8, 0x13, 0x4b, 0x94, 0xda, 0xc6, 0xb5,
	0xc0, 0x76, 0x15, 0xbb, 0x95, 0xfb, 0x16, 0x3c, 0x56, 0xc7, 0x0e, 0x0c, 0x4c, 0x11, 0x4a, 0xdf,
	0xa2, 0x13, 0xca, 0xc7, 0x50, 0x09, 0x09, 0x16, 0xfb, 0xf8, 0x2f, 0x9f, 0x9f, 0x8f, 0x8f, 0x87,
	0x44, 0xb6, 0xce, 0xf0, 0x3c, 0xe3, 0x12, 0xad, 0xc6, 0xc8, 0x1e, 0x1c, 0xcd, 0x7a, 0x41, 0x35,
	0x12, 0x9a, 0xa5, 0x39, 0x7d, 0x59, 0x4a, 0x02, 0x17, 0xb9, 0x32, 0xca, 0x3f, 0xaa, 0xe7, 0xfd,
	0xdb, 0x3f, 0x7c, 0xd5, 0x9a, 0xaa, 0x99, 0xa6, 0xf9, 0x8a, 0x92, 0xd4, 0xd8, 0xc6, 0xdd, 0x3f,
	0x67, 0x8a, 0xa9, 0x5a, 0xa2, 0x4a, 0x35, 0xd3, 0x8b, 0x0f, 0xe0, 0x75, 0x1f, 0x34, 0x4b, 0xea,
	0x77, 0xa6, 0xd6, 0xbf, 0xf4, 0x3a, 0xc6, 0xf6, 0xc0, 0x00, 0x0c, 0xbb, 0xd7, 0x67, 0xb0, 0x06,
	0xc2, 0xc7, 0x96, 0x35, 0xb5, 0xd1, 0xff, 0x4d, 0x11, 0x3a, 0x49, 0xc7, 0x58, 0xff, 0xc9, 0x3b,
	0xe6, 0x32, 0x35, 0x36, 0xe5, 0xa4, 0xd7, 0x19, 0x80, 0xe1, 0x49, 0x74, 0x57, 0x16, 0xa1, 0x1b,
	0xcb, 0xa9, 0x8d, 0xef, 0xf7, 0x45, 0x78, 0xc5, 0xb8, 0x79, 0xcb, 0x66, 0x10, 0x2b, 0x71, 0x90,
	0xb0, 0x52, 0x52, 0x11, 0x8a, 0xb0, 0x12, 0x42, 0x49, 0x58, 0x5d, 0x4e, 0x5c, 0x5e, 0x99, 0x88,
	0x1f, 0x7b, 0xae, 0xe6, 0x4c, 0xd2, 0xbc, 0xf7, 0x6f, 0x00, 0x86, 0xa7, 0xd1, 0x78, 0x5f, 0x84,
	0x23, 0xc6, 0xcd, 0x7c, 0xd9, 0x60, 0xb0, 0xd2, 0x42, 0xe9, 0x76, 0x1b, 0x69, 0xf2, 0xda, 0x7c,
	0x18, 0x4e, 0x30, 0x9e, 0x10, 0x92, 0x53, 0xad, 0x93, 0x16, 0x10, 0xc5, 0x9b, 0x32, 0x00, 0xdb,
	0x32, 0x00, 0x5f, 0x65, 0x00, 0xde, 0x77, 0x81, 0xb3, 0xdd, 0x05, 0xce, 0xe7, 0x2e, 0x70, 0x9e,
	0xd1, 0xef, 0xb9, 0x7e, 0xd4, 0x39, 0x73, 0xeb, 0xa2, 0x6e, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x33, 0xcd, 0x43, 0x5a, 0xaf, 0x01, 0x00, 0x00,
}

func (m *MsgRefundTx) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRefundTx) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRefundTx) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintMsgRefund(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.InTxID) > 0 {
		i -= len(m.InTxID)
		copy(dAtA[i:], m.InTxID)
		i = encodeVarintMsgRefund(dAtA, i, uint64(len(m.InTxID)))
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.Tx.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMsgRefund(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintMsgRefund(dAtA []byte, offset int, v uint64) int {
	offset -= sovMsgRefund(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRefundTx) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Tx.Size()
	n += 1 + l + sovMsgRefund(uint64(l))
	l = len(m.InTxID)
	if l > 0 {
		n += 1 + l + sovMsgRefund(uint64(l))
	}
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovMsgRefund(uint64(l))
	}
	return n
}

func sovMsgRefund(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMsgRefund(x uint64) (n int) {
	return sovMsgRefund(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRefundTx) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgRefund
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRefundTx: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRefundTx: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tx", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgRefund
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgRefund
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgRefund
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Tx.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InTxID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgRefund
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgRefund
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgRefund
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InTxID = gitlab_com_mayachain_mayanode_common.TxID(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgRefund
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgRefund
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgRefund
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = append(m.Signer[:0], dAtA[iNdEx:postIndex]...)
			if m.Signer == nil {
				m.Signer = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgRefund(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsgRefund
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMsgRefund
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMsgRefund(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMsgRefund
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgRefund
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgRefund
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMsgRefund
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMsgRefund
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMsgRefund
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMsgRefund        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMsgRefund          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMsgRefund = fmt.Errorf("proto: unexpected end of group")
)
