// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mayachain/v1/x/mayachain/types/msg_unbond.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	common "gitlab.com/mayachain/mayanode/common"
	gitlab_com_mayachain_mayanode_common "gitlab.com/mayachain/mayanode/common"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgUnBond struct {
	TxIn                common.Tx                                     `protobuf:"bytes,1,opt,name=tx_in,json=txIn,proto3" json:"tx_in"`
	NodeAddress         github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,2,opt,name=node_address,json=nodeAddress,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"node_address,omitempty"`
	BondAddress         gitlab_com_mayachain_mayanode_common.Address  `protobuf:"bytes,5,opt,name=bond_address,json=bondAddress,proto3,casttype=gitlab.com/mayachain/mayanode/common.Address" json:"bond_address,omitempty"`
	Signer              github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,7,opt,name=signer,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"signer,omitempty"`
	BondProviderAddress github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,8,opt,name=bond_provider_address,json=bondProviderAddress,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"bond_provider_address,omitempty"`
	Asset               common.Asset                                  `protobuf:"bytes,9,opt,name=asset,proto3" json:"asset"`
	Units               github_com_cosmos_cosmos_sdk_types.Uint       `protobuf:"bytes,10,opt,name=units,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Uint" json:"units"`
}

func (m *MsgUnBond) Reset()         { *m = MsgUnBond{} }
func (m *MsgUnBond) String() string { return proto.CompactTextString(m) }
func (*MsgUnBond) ProtoMessage()    {}
func (*MsgUnBond) Descriptor() ([]byte, []int) {
	return fileDescriptor_6278ba4f4a5fc748, []int{0}
}
func (m *MsgUnBond) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUnBond) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUnBond.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUnBond) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUnBond.Merge(m, src)
}
func (m *MsgUnBond) XXX_Size() int {
	return m.Size()
}
func (m *MsgUnBond) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUnBond.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUnBond proto.InternalMessageInfo

func (m *MsgUnBond) GetTxIn() common.Tx {
	if m != nil {
		return m.TxIn
	}
	return common.Tx{}
}

func (m *MsgUnBond) GetNodeAddress() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.NodeAddress
	}
	return nil
}

func (m *MsgUnBond) GetBondAddress() gitlab_com_mayachain_mayanode_common.Address {
	if m != nil {
		return m.BondAddress
	}
	return ""
}

func (m *MsgUnBond) GetSigner() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.Signer
	}
	return nil
}

func (m *MsgUnBond) GetBondProviderAddress() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.BondProviderAddress
	}
	return nil
}

func (m *MsgUnBond) GetAsset() common.Asset {
	if m != nil {
		return m.Asset
	}
	return common.Asset{}
}

func init() {
	proto.RegisterType((*MsgUnBond)(nil), "types.MsgUnBond")
}

func init() {
	proto.RegisterFile("mayachain/v1/x/mayachain/types/msg_unbond.proto", fileDescriptor_6278ba4f4a5fc748)
}

var fileDescriptor_6278ba4f4a5fc748 = []byte{
	// 378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xc1, 0x4a, 0xc3, 0x30,
	0x18, 0xc7, 0x5b, 0x59, 0xa7, 0xcb, 0xe6, 0xa5, 0x2a, 0x94, 0x1d, 0xda, 0x22, 0x88, 0x13, 0xdc,
	0xe2, 0xf4, 0x09, 0x56, 0xf0, 0xb0, 0x83, 0x20, 0x73, 0xbb, 0x78, 0x19, 0x5d, 0x5b, 0xb2, 0xa0,
	0x4d, 0x46, 0x93, 0x8d, 0xee, 0xe8, 0x1b, 0xf8, 0x58, 0x3b, 0xee, 0x28, 0x1e, 0x8a, 0x6c, 0x6f,
	0xb1, 0x93, 0xa4, 0x49, 0xa7, 0x22, 0x88, 0xec, 0x94, 0x2f, 0x5f, 0xf2, 0xff, 0xf1, 0xff, 0xe7,
	0x0b, 0x80, 0xb1, 0x3f, 0xf7, 0x83, 0xb1, 0x8f, 0x09, 0x9c, 0xb5, 0x61, 0xfa, 0x6d, 0xcb, 0xe7,
	0x93, 0x88, 0xc1, 0x98, 0xa1, 0xe1, 0x94, 0x8c, 0x28, 0x09, 0x5b, 0x93, 0x84, 0x72, 0x6a, 0x1a,
	0x79, 0xbf, 0xee, 0xfe, 0xd0, 0x05, 0x34, 0x8e, 0x29, 0x51, 0x8b, 0xbc, 0x58, 0x3f, 0x46, 0x14,
	0xd1, 0xbc, 0x84, 0xa2, 0x92, 0xdd, 0xd3, 0x97, 0x12, 0xa8, 0xdc, 0x31, 0x34, 0x20, 0x1e, 0x25,
	0xa1, 0x79, 0x06, 0x0c, 0x9e, 0x0e, 0x31, 0xb1, 0x74, 0x57, 0x6f, 0x54, 0xaf, 0x41, 0x4b, 0x11,
	0xfa, 0xa9, 0x57, 0x5a, 0x64, 0x8e, 0xd6, 0x2b, 0xf1, 0xb4, 0x4b, 0xcc, 0x3e, 0xa8, 0x11, 0x1a,
	0x46, 0x43, 0x3f, 0x0c, 0x93, 0x88, 0x31, 0x6b, 0xcf, 0xd5, 0x1b, 0x35, 0xaf, 0xbd, 0xc9, 0x9c,
	0x26, 0xc2, 0x7c, 0x3c, 0x1d, 0x09, 0x1d, 0x0c, 0x28, 0x8b, 0x29, 0x53, 0x4b, 0x93, 0x85, 0x4f,
	0x32, 0x42, 0xab, 0x13, 0x04, 0x1d, 0x29, 0xec, 0x55, 0x05, 0x46, 0x6d, 0xcc, 0x07, 0x50, 0x13,
	0xb9, 0xb6, 0x54, 0xc3, 0xd5, 0x1b, 0x15, 0xef, 0x6a, 0x93, 0x39, 0x97, 0x08, 0xf3, 0x67, 0x5f,
	0x52, 0xbf, 0x72, 0x8a, 0x4a, 0xe8, 0x8b, 0x98, 0x5b, 0xa8, 0xa0, 0x14, 0xd0, 0x2e, 0x28, 0x33,
	0x8c, 0x48, 0x94, 0x58, 0xfb, 0xbb, 0x9a, 0x54, 0x00, 0x33, 0x02, 0x27, 0xb9, 0xbf, 0x49, 0x42,
	0x67, 0x38, 0x8c, 0x92, 0xad, 0xd1, 0x83, 0x5d, 0xc9, 0x47, 0x82, 0x77, 0xaf, 0x70, 0x85, 0xe3,
	0x0b, 0x60, 0xf8, 0x8c, 0x45, 0xdc, 0xaa, 0xe4, 0x33, 0x38, 0x2c, 0x66, 0xd0, 0x11, 0x4d, 0x35,
	0x06, 0x79, 0xc3, 0xbc, 0x05, 0xc6, 0x94, 0x60, 0xce, 0x2c, 0x90, 0x3f, 0x15, 0x14, 0x67, 0xef,
	0x99, 0x73, 0xfe, 0x0f, 0x17, 0x03, 0x4c, 0x78, 0x4f, 0xaa, 0xbd, 0xee, 0x62, 0x65, 0xeb, 0xcb,
	0x95, 0xad, 0x7f, 0xac, 0x6c, 0xfd, 0x75, 0x6d, 0x6b, 0xcb, 0xb5, 0xad, 0xbd, 0xad, 0x6d, 0xed,
	0x11, 0xfe, 0xfd, 0xf0, 0xbf, 0xbe, 0xe7, 0xa8, 0x9c, 0xff, 0xaa, 0x9b, 0xcf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xa4, 0xca, 0xc1, 0x16, 0xc7, 0x02, 0x00, 0x00,
}

func (m *MsgUnBond) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUnBond) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUnBond) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Units.Size()
		i -= size
		if _, err := m.Units.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMsgUnbond(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x52
	{
		size, err := m.Asset.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMsgUnbond(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	if len(m.BondProviderAddress) > 0 {
		i -= len(m.BondProviderAddress)
		copy(dAtA[i:], m.BondProviderAddress)
		i = encodeVarintMsgUnbond(dAtA, i, uint64(len(m.BondProviderAddress)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintMsgUnbond(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.BondAddress) > 0 {
		i -= len(m.BondAddress)
		copy(dAtA[i:], m.BondAddress)
		i = encodeVarintMsgUnbond(dAtA, i, uint64(len(m.BondAddress)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.NodeAddress) > 0 {
		i -= len(m.NodeAddress)
		copy(dAtA[i:], m.NodeAddress)
		i = encodeVarintMsgUnbond(dAtA, i, uint64(len(m.NodeAddress)))
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.TxIn.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMsgUnbond(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintMsgUnbond(dAtA []byte, offset int, v uint64) int {
	offset -= sovMsgUnbond(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUnBond) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.TxIn.Size()
	n += 1 + l + sovMsgUnbond(uint64(l))
	l = len(m.NodeAddress)
	if l > 0 {
		n += 1 + l + sovMsgUnbond(uint64(l))
	}
	l = len(m.BondAddress)
	if l > 0 {
		n += 1 + l + sovMsgUnbond(uint64(l))
	}
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovMsgUnbond(uint64(l))
	}
	l = len(m.BondProviderAddress)
	if l > 0 {
		n += 1 + l + sovMsgUnbond(uint64(l))
	}
	l = m.Asset.Size()
	n += 1 + l + sovMsgUnbond(uint64(l))
	l = m.Units.Size()
	n += 1 + l + sovMsgUnbond(uint64(l))
	return n
}

func sovMsgUnbond(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMsgUnbond(x uint64) (n int) {
	return sovMsgUnbond(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUnBond) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgUnbond
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUnBond: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUnBond: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxIn", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgUnbond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgUnbond
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgUnbond
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TxIn.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgUnbond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgUnbond
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgUnbond
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeAddress = append(m.NodeAddress[:0], dAtA[iNdEx:postIndex]...)
			if m.NodeAddress == nil {
				m.NodeAddress = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgUnbond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgUnbond
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgUnbond
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BondAddress = gitlab_com_mayachain_mayanode_common.Address(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgUnbond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgUnbond
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgUnbond
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = append(m.Signer[:0], dAtA[iNdEx:postIndex]...)
			if m.Signer == nil {
				m.Signer = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondProviderAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgUnbond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgUnbond
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgUnbond
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BondProviderAddress = append(m.BondProviderAddress[:0], dAtA[iNdEx:postIndex]...)
			if m.BondProviderAddress == nil {
				m.BondProviderAddress = []byte{}
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Asset", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgUnbond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgUnbond
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgUnbond
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Asset.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Units", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgUnbond
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgUnbond
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgUnbond
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Units.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgUnbond(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsgUnbond
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMsgUnbond
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMsgUnbond(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMsgUnbond
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgUnbond
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgUnbond
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMsgUnbond
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMsgUnbond
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMsgUnbond
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMsgUnbond        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMsgUnbond          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMsgUnbond = fmt.Errorf("proto: unexpected end of group")
)
