// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mayachain/v1/x/mayachain/types/msg_errata.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	gitlab_com_mayachain_mayanode_common "gitlab.com/mayachain/mayanode/common"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgErrataTx struct {
	TxID   gitlab_com_mayachain_mayanode_common.TxID     `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3,casttype=gitlab.com/mayachain/mayanode/common.TxID" json:"tx_id,omitempty"`
	Chain  gitlab_com_mayachain_mayanode_common.Chain    `protobuf:"bytes,2,opt,name=chain,proto3,casttype=gitlab.com/mayachain/mayanode/common.Chain" json:"chain,omitempty"`
	Signer github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,3,opt,name=signer,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"signer,omitempty"`
}

func (m *MsgErrataTx) Reset()         { *m = MsgErrataTx{} }
func (m *MsgErrataTx) String() string { return proto.CompactTextString(m) }
func (*MsgErrataTx) ProtoMessage()    {}
func (*MsgErrataTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdd29a5086cd4cf4, []int{0}
}
func (m *MsgErrataTx) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgErrataTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgErrataTx.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgErrataTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgErrataTx.Merge(m, src)
}
func (m *MsgErrataTx) XXX_Size() int {
	return m.Size()
}
func (m *MsgErrataTx) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgErrataTx.DiscardUnknown(m)
}

var xxx_messageInfo_MsgErrataTx proto.InternalMessageInfo

func (m *MsgErrataTx) GetTxID() gitlab_com_mayachain_mayanode_common.TxID {
	if m != nil {
		return m.TxID
	}
	return ""
}

func (m *MsgErrataTx) GetChain() gitlab_com_mayachain_mayanode_common.Chain {
	if m != nil {
		return m.Chain
	}
	return ""
}

func (m *MsgErrataTx) GetSigner() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.Signer
	}
	return nil
}

func init() {
	proto.RegisterType((*MsgErrataTx)(nil), "types.MsgErrataTx")
}

func init() {
	proto.RegisterFile("mayachain/v1/x/mayachain/types/msg_errata.proto", fileDescriptor_bdd29a5086cd4cf4)
}

var fileDescriptor_bdd29a5086cd4cf4 = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0xcf, 0x4d, 0xac, 0x4c,
	0x4c, 0xce, 0x48, 0xcc, 0xcc, 0xd3, 0x2f, 0x33, 0xd4, 0xaf, 0x40, 0xe2, 0x96, 0x54, 0x16, 0xa4,
	0x16, 0xeb, 0xe7, 0x16, 0xa7, 0xc7, 0xa7, 0x16, 0x15, 0x25, 0x96, 0x24, 0xea, 0x15, 0x14, 0xe5,
	0x97, 0xe4, 0x0b, 0xb1, 0x82, 0xc5, 0xa5, 0x44, 0xd2, 0xf3, 0xd3, 0xf3, 0xc1, 0x22, 0xfa, 0x20,
	0x16, 0x44, 0x52, 0xe9, 0x15, 0x23, 0x17, 0xb7, 0x6f, 0x71, 0xba, 0x2b, 0x58, 0x43, 0x48, 0x85,
	0x90, 0x17, 0x17, 0x6b, 0x49, 0x45, 0x7c, 0x66, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0xa7, 0x93,
	0xe9, 0xa3, 0x7b, 0xf2, 0x2c, 0x21, 0x15, 0x9e, 0x2e, 0xbf, 0xee, 0xc9, 0x6b, 0xa6, 0x67, 0x96,
	0xe4, 0x24, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0x22, 0x59, 0x0a, 0x62, 0xe5, 0xe5, 0xa7, 0xa4, 0xea,
	0x27, 0xe7, 0xe7, 0xe6, 0xe6, 0xe7, 0xe9, 0x81, 0x14, 0x07, 0xb1, 0x94, 0x54, 0x78, 0xa6, 0x08,
	0xb9, 0x70, 0xb1, 0x82, 0xd5, 0x48, 0x30, 0x81, 0xcd, 0xd2, 0xfb, 0x75, 0x4f, 0x5e, 0x8b, 0x28,
	0x33, 0x9c, 0x41, 0xa2, 0x41, 0x10, 0xcd, 0x42, 0x9e, 0x5c, 0x6c, 0xc5, 0x99, 0xe9, 0x79, 0xa9,
	0x45, 0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0x3c, 0x4e, 0x86, 0xbf, 0xee, 0xc9, 0xeb, 0xa6, 0x67, 0x96,
	0x64, 0x94, 0x42, 0x8c, 0x49, 0xce, 0x2f, 0xce, 0xcd, 0x2f, 0x86, 0x52, 0xba, 0xc5, 0x29, 0xd9,
	0x90, 0x70, 0xd0, 0x73, 0x4c, 0x4e, 0x76, 0x4c, 0x49, 0x29, 0x4a, 0x2d, 0x2e, 0x0e, 0x82, 0x1a,
	0xe0, 0xe4, 0x79, 0xe2, 0x91, 0x1c, 0xe3, 0x85, 0x47, 0x72, 0x8c, 0x0f, 0x1e, 0xc9, 0x31, 0x4e,
	0x78, 0x2c, 0xc7, 0x70, 0xe1, 0xb1, 0x1c, 0xc3, 0x8d, 0xc7, 0x72, 0x0c, 0x51, 0xfa, 0xf8, 0xdd,
	0x85, 0x11, 0xca, 0x49, 0x6c, 0xe0, 0xe0, 0x33, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xb0, 0xa5,
	0x7a, 0x64, 0x8e, 0x01, 0x00, 0x00,
}

func (m *MsgErrataTx) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgErrataTx) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgErrataTx) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintMsgErrata(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Chain) > 0 {
		i -= len(m.Chain)
		copy(dAtA[i:], m.Chain)
		i = encodeVarintMsgErrata(dAtA, i, uint64(len(m.Chain)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.TxID) > 0 {
		i -= len(m.TxID)
		copy(dAtA[i:], m.TxID)
		i = encodeVarintMsgErrata(dAtA, i, uint64(len(m.TxID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMsgErrata(dAtA []byte, offset int, v uint64) int {
	offset -= sovMsgErrata(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgErrataTx) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TxID)
	if l > 0 {
		n += 1 + l + sovMsgErrata(uint64(l))
	}
	l = len(m.Chain)
	if l > 0 {
		n += 1 + l + sovMsgErrata(uint64(l))
	}
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovMsgErrata(uint64(l))
	}
	return n
}

func sovMsgErrata(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMsgErrata(x uint64) (n int) {
	return sovMsgErrata(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgErrataTx) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgErrata
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgErrataTx: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgErrataTx: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgErrata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgErrata
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgErrata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxID = gitlab_com_mayachain_mayanode_common.TxID(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Chain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgErrata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgErrata
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgErrata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Chain = gitlab_com_mayachain_mayanode_common.Chain(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgErrata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgErrata
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgErrata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = append(m.Signer[:0], dAtA[iNdEx:postIndex]...)
			if m.Signer == nil {
				m.Signer = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgErrata(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsgErrata
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMsgErrata
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMsgErrata(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMsgErrata
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgErrata
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgErrata
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMsgErrata
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMsgErrata
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMsgErrata
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMsgErrata        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMsgErrata          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMsgErrata = fmt.Errorf("proto: unexpected end of group")
)
