// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mayachain/v1/x/mayachain/types/type_tx_out.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	common "gitlab.com/mayachain/mayanode/common"
	gitlab_com_mayachain_mayanode_common "gitlab.com/mayachain/mayanode/common"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type TxOutItem struct {
	Chain                 gitlab_com_mayachain_mayanode_common.Chain   `protobuf:"bytes,1,opt,name=chain,proto3,casttype=gitlab.com/mayachain/mayanode/common.Chain" json:"chain,omitempty"`
	ToAddress             gitlab_com_mayachain_mayanode_common.Address `protobuf:"bytes,2,opt,name=to_address,json=toAddress,proto3,casttype=gitlab.com/mayachain/mayanode/common.Address" json:"to_address,omitempty"`
	VaultPubKey           gitlab_com_mayachain_mayanode_common.PubKey  `protobuf:"bytes,3,opt,name=vault_pub_key,json=vaultPubKey,proto3,casttype=gitlab.com/mayachain/mayanode/common.PubKey" json:"vault_pub_key,omitempty"`
	Coin                  common.Coin                                  `protobuf:"bytes,4,opt,name=coin,proto3" json:"coin"`
	Memo                  string                                       `protobuf:"bytes,5,opt,name=memo,proto3" json:"memo,omitempty"`
	MaxGas                gitlab_com_mayachain_mayanode_common.Gas     `protobuf:"bytes,6,rep,name=max_gas,json=maxGas,proto3,castrepeated=gitlab.com/mayachain/mayanode/common.Gas" json:"max_gas"`
	GasRate               int64                                        `protobuf:"varint,7,opt,name=gas_rate,json=gasRate,proto3" json:"gas_rate,omitempty"`
	InHash                gitlab_com_mayachain_mayanode_common.TxID    `protobuf:"bytes,8,opt,name=in_hash,json=inHash,proto3,casttype=gitlab.com/mayachain/mayanode/common.TxID" json:"in_hash,omitempty"`
	OutHash               gitlab_com_mayachain_mayanode_common.TxID    `protobuf:"bytes,9,opt,name=out_hash,json=outHash,proto3,casttype=gitlab.com/mayachain/mayanode/common.TxID" json:"out_hash,omitempty"`
	ModuleName            string                                       `protobuf:"bytes,10,opt,name=module_name,json=-,proto3" json:"-"`
	Aggregator            string                                       `protobuf:"bytes,11,opt,name=aggregator,proto3" json:"aggregator,omitempty"`
	AggregatorTargetAsset string                                       `protobuf:"bytes,12,opt,name=aggregator_target_asset,json=aggregatorTargetAsset,proto3" json:"aggregator_target_asset,omitempty"`
	AggregatorTargetLimit *github_com_cosmos_cosmos_sdk_types.Uint     `protobuf:"bytes,13,opt,name=aggregator_target_limit,json=aggregatorTargetLimit,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Uint" json:"aggregator_target_limit,omitempty"`
}

func (m *TxOutItem) Reset()      { *m = TxOutItem{} }
func (*TxOutItem) ProtoMessage() {}
func (*TxOutItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_3731271d51a4f38c, []int{0}
}
func (m *TxOutItem) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TxOutItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TxOutItem.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TxOutItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxOutItem.Merge(m, src)
}
func (m *TxOutItem) XXX_Size() int {
	return m.Size()
}
func (m *TxOutItem) XXX_DiscardUnknown() {
	xxx_messageInfo_TxOutItem.DiscardUnknown(m)
}

var xxx_messageInfo_TxOutItem proto.InternalMessageInfo

type TxOut struct {
	Height  int64       `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	TxArray []TxOutItem `protobuf:"bytes,2,rep,name=tx_array,json=txArray,proto3" json:"tx_array"`
}

func (m *TxOut) Reset()      { *m = TxOut{} }
func (*TxOut) ProtoMessage() {}
func (*TxOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_3731271d51a4f38c, []int{1}
}
func (m *TxOut) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TxOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TxOut.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TxOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxOut.Merge(m, src)
}
func (m *TxOut) XXX_Size() int {
	return m.Size()
}
func (m *TxOut) XXX_DiscardUnknown() {
	xxx_messageInfo_TxOut.DiscardUnknown(m)
}

var xxx_messageInfo_TxOut proto.InternalMessageInfo

func init() {
	proto.RegisterType((*TxOutItem)(nil), "types.TxOutItem")
	proto.RegisterType((*TxOut)(nil), "types.TxOut")
}

func init() {
	proto.RegisterFile("mayachain/v1/x/mayachain/types/type_tx_out.proto", fileDescriptor_3731271d51a4f38c)
}

var fileDescriptor_3731271d51a4f38c = []byte{
	// 594 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0xed, 0xe6, 0x7b, 0xd3, 0x4a, 0x68, 0xc5, 0xc7, 0x52, 0x09, 0x3b, 0xea, 0x01, 0xc2,
	0x47, 0xe2, 0x16, 0x24, 0x0e, 0xdc, 0x5a, 0x2a, 0xda, 0x0a, 0xa4, 0x22, 0xd3, 0x0a, 0xc4, 0x65,
	0xb5, 0x49, 0x56, 0x6b, 0xab, 0x59, 0x6f, 0xe5, 0x1d, 0x57, 0xce, 0xad, 0x8f, 0xc0, 0x95, 0x57,
	0xe0, 0x49, 0x72, 0xec, 0xb1, 0x42, 0xc8, 0xd0, 0xf4, 0xc6, 0x23, 0xe4, 0x84, 0xbc, 0x4e, 0x69,
	0x51, 0x11, 0x8a, 0xb8, 0x78, 0x67, 0x76, 0xf6, 0xff, 0x9b, 0x1d, 0x7b, 0xc6, 0x68, 0x55, 0xb2,
	0x11, 0xeb, 0x07, 0x2c, 0x8c, 0xbc, 0xa3, 0x35, 0x2f, 0xf5, 0x2e, 0x5d, 0x18, 0x1d, 0x72, 0x6d,
	0x9e, 0x14, 0x52, 0xaa, 0x12, 0xe8, 0x1e, 0xc6, 0x0a, 0x14, 0xae, 0x98, 0xc0, 0x72, 0xeb, 0x0f,
	0x61, 0x5f, 0x49, 0xa9, 0xa2, 0xd9, 0x52, 0x1c, 0x5c, 0xbe, 0x29, 0x94, 0x50, 0xc6, 0xf4, 0x72,
	0xab, 0xd8, 0x5d, 0xf9, 0x5c, 0x45, 0x8d, 0xbd, 0x74, 0x37, 0x81, 0x1d, 0xe0, 0x12, 0x6f, 0xa2,
	0x8a, 0x61, 0x10, 0xbb, 0x65, 0xb7, 0x1b, 0x1b, 0xdd, 0x69, 0xe6, 0x3e, 0x12, 0x21, 0x0c, 0x59,
	0xaf, 0xdb, 0x57, 0xf2, 0xca, 0x6d, 0x72, 0x2b, 0x52, 0x03, 0x7e, 0x91, 0xe2, 0x65, 0xbe, 0xeb,
	0x17, 0x62, 0xbc, 0x8b, 0x10, 0x28, 0xca, 0x06, 0x83, 0x98, 0x6b, 0x4d, 0x16, 0x0c, 0x6a, 0x75,
	0x9a, 0xb9, 0x4f, 0xe6, 0x42, 0xad, 0x17, 0x3a, 0xbf, 0x01, 0x6a, 0x66, 0xe2, 0x77, 0x68, 0xe9,
	0x88, 0x25, 0x43, 0xa0, 0x87, 0x49, 0x8f, 0x1e, 0xf0, 0x11, 0x29, 0x19, 0xa6, 0x37, 0xcd, 0xdc,
	0xc7, 0x73, 0x31, 0xdf, 0x26, 0xbd, 0xd7, 0x7c, 0xe4, 0x37, 0x0d, 0xa5, 0x70, 0xf0, 0x7d, 0x54,
	0xee, 0xab, 0x30, 0x22, 0xe5, 0x96, 0xdd, 0x6e, 0x3e, 0x5d, 0xec, 0x5e, 0x54, 0xa2, 0xc2, 0x68,
	0xa3, 0x3c, 0xce, 0x5c, 0xcb, 0x37, 0x71, 0x8c, 0x51, 0x59, 0x72, 0xa9, 0x48, 0x25, 0xcf, 0xe9,
	0x1b, 0x1b, 0xbf, 0x47, 0x35, 0xc9, 0x52, 0x2a, 0x98, 0x26, 0xd5, 0x56, 0xe9, 0x9a, 0x7c, 0x35,
	0x97, 0x7f, 0xf9, 0xee, 0xb6, 0xe7, 0xba, 0xdc, 0x16, 0xd3, 0x7e, 0x55, 0xb2, 0x74, 0x8b, 0x69,
	0x7c, 0x17, 0xd5, 0x05, 0xd3, 0x34, 0x66, 0xc0, 0x49, 0xad, 0x65, 0xb7, 0x4b, 0x7e, 0x4d, 0x30,
	0xed, 0x33, 0xe0, 0xf8, 0x15, 0xaa, 0x85, 0x11, 0x0d, 0x98, 0x0e, 0x48, 0xdd, 0x94, 0xdf, 0x99,
	0x66, 0xee, 0xc3, 0xb9, 0x32, 0xec, 0xa5, 0x3b, 0x9b, 0x7e, 0x35, 0x8c, 0xb6, 0x99, 0x0e, 0xf0,
	0x36, 0xaa, 0xab, 0x04, 0x0a, 0x50, 0xe3, 0x7f, 0x40, 0x35, 0x95, 0x80, 0x21, 0xdd, 0x43, 0x4d,
	0xa9, 0x06, 0xc9, 0x90, 0xd3, 0x88, 0x49, 0x4e, 0x90, 0x81, 0x55, 0x7e, 0x66, 0xae, 0xdd, 0xf1,
	0xed, 0x0e, 0x76, 0x10, 0x62, 0x42, 0xc4, 0x5c, 0x30, 0x50, 0x31, 0x69, 0x9a, 0xd7, 0x77, 0x65,
	0x07, 0x3f, 0x47, 0x77, 0x2e, 0x3d, 0x0a, 0x2c, 0x16, 0x1c, 0x28, 0xd3, 0x9a, 0x03, 0x59, 0x34,
	0x87, 0x6f, 0x5d, 0x86, 0xf7, 0x4c, 0x74, 0x3d, 0x0f, 0x62, 0xf1, 0x37, 0xdd, 0x30, 0x94, 0x21,
	0x90, 0xa5, 0xa2, 0x2f, 0xc6, 0x99, 0x6b, 0x7f, 0xcd, 0xdc, 0x07, 0x22, 0x84, 0x20, 0x29, 0x6a,
	0xea, 0x2b, 0x2d, 0x95, 0x9e, 0x2d, 0x1d, 0x3d, 0x38, 0x28, 0x06, 0xaa, 0xbb, 0x1f, 0x46, 0x70,
	0x3d, 0xd1, 0x9b, 0x9c, 0xb6, 0xf2, 0x01, 0x55, 0xcc, 0x68, 0xe0, 0xdb, 0xa8, 0x1a, 0xf0, 0x50,
	0x04, 0x60, 0xe6, 0xa2, 0xe4, 0xcf, 0x3c, 0xbc, 0x86, 0xea, 0x90, 0x52, 0x16, 0xc7, 0x6c, 0x44,
	0x16, 0x4c, 0x1f, 0xdc, 0xe8, 0x16, 0xd8, 0xdf, 0x23, 0x35, 0x6b, 0xa5, 0x1a, 0xa4, 0xeb, 0xf9,
	0xb1, 0x17, 0xe5, 0xe3, 0x6f, 0x2d, 0x7b, 0x63, 0x7f, 0x7c, 0xe6, 0x58, 0xa7, 0x67, 0x8e, 0x75,
	0x3c, 0x71, 0xac, 0xf1, 0xc4, 0xb1, 0x4f, 0x26, 0x8e, 0xfd, 0x63, 0xe2, 0xd8, 0x9f, 0xce, 0x1d,
	0xeb, 0xe4, 0xdc, 0xb1, 0x4e, 0xcf, 0x1d, 0xeb, 0xa3, 0xf7, 0xef, 0x6f, 0x72, 0xed, 0xef, 0xd0,
	0xab, 0x9a, 0x99, 0x7e, 0xf6, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x47, 0xaa, 0xa4, 0x83, 0x46, 0x04,
	0x00, 0x00,
}

func (m *TxOutItem) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TxOutItem) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TxOutItem) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AggregatorTargetLimit != nil {
		{
			size := m.AggregatorTargetLimit.Size()
			i -= size
			if _, err := m.AggregatorTargetLimit.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintTypeTxOut(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x6a
	}
	if len(m.AggregatorTargetAsset) > 0 {
		i -= len(m.AggregatorTargetAsset)
		copy(dAtA[i:], m.AggregatorTargetAsset)
		i = encodeVarintTypeTxOut(dAtA, i, uint64(len(m.AggregatorTargetAsset)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.Aggregator) > 0 {
		i -= len(m.Aggregator)
		copy(dAtA[i:], m.Aggregator)
		i = encodeVarintTypeTxOut(dAtA, i, uint64(len(m.Aggregator)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.ModuleName) > 0 {
		i -= len(m.ModuleName)
		copy(dAtA[i:], m.ModuleName)
		i = encodeVarintTypeTxOut(dAtA, i, uint64(len(m.ModuleName)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.OutHash) > 0 {
		i -= len(m.OutHash)
		copy(dAtA[i:], m.OutHash)
		i = encodeVarintTypeTxOut(dAtA, i, uint64(len(m.OutHash)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.InHash) > 0 {
		i -= len(m.InHash)
		copy(dAtA[i:], m.InHash)
		i = encodeVarintTypeTxOut(dAtA, i, uint64(len(m.InHash)))
		i--
		dAtA[i] = 0x42
	}
	if m.GasRate != 0 {
		i = encodeVarintTypeTxOut(dAtA, i, uint64(m.GasRate))
		i--
		dAtA[i] = 0x38
	}
	if len(m.MaxGas) > 0 {
		for iNdEx := len(m.MaxGas) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MaxGas[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypeTxOut(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.Memo) > 0 {
		i -= len(m.Memo)
		copy(dAtA[i:], m.Memo)
		i = encodeVarintTypeTxOut(dAtA, i, uint64(len(m.Memo)))
		i--
		dAtA[i] = 0x2a
	}
	{
		size, err := m.Coin.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypeTxOut(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.VaultPubKey) > 0 {
		i -= len(m.VaultPubKey)
		copy(dAtA[i:], m.VaultPubKey)
		i = encodeVarintTypeTxOut(dAtA, i, uint64(len(m.VaultPubKey)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ToAddress) > 0 {
		i -= len(m.ToAddress)
		copy(dAtA[i:], m.ToAddress)
		i = encodeVarintTypeTxOut(dAtA, i, uint64(len(m.ToAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Chain) > 0 {
		i -= len(m.Chain)
		copy(dAtA[i:], m.Chain)
		i = encodeVarintTypeTxOut(dAtA, i, uint64(len(m.Chain)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TxOut) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TxOut) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TxOut) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TxArray) > 0 {
		for iNdEx := len(m.TxArray) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TxArray[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypeTxOut(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Height != 0 {
		i = encodeVarintTypeTxOut(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypeTxOut(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypeTxOut(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *TxOutItem) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Chain)
	if l > 0 {
		n += 1 + l + sovTypeTxOut(uint64(l))
	}
	l = len(m.ToAddress)
	if l > 0 {
		n += 1 + l + sovTypeTxOut(uint64(l))
	}
	l = len(m.VaultPubKey)
	if l > 0 {
		n += 1 + l + sovTypeTxOut(uint64(l))
	}
	l = m.Coin.Size()
	n += 1 + l + sovTypeTxOut(uint64(l))
	l = len(m.Memo)
	if l > 0 {
		n += 1 + l + sovTypeTxOut(uint64(l))
	}
	if len(m.MaxGas) > 0 {
		for _, e := range m.MaxGas {
			l = e.Size()
			n += 1 + l + sovTypeTxOut(uint64(l))
		}
	}
	if m.GasRate != 0 {
		n += 1 + sovTypeTxOut(uint64(m.GasRate))
	}
	l = len(m.InHash)
	if l > 0 {
		n += 1 + l + sovTypeTxOut(uint64(l))
	}
	l = len(m.OutHash)
	if l > 0 {
		n += 1 + l + sovTypeTxOut(uint64(l))
	}
	l = len(m.ModuleName)
	if l > 0 {
		n += 1 + l + sovTypeTxOut(uint64(l))
	}
	l = len(m.Aggregator)
	if l > 0 {
		n += 1 + l + sovTypeTxOut(uint64(l))
	}
	l = len(m.AggregatorTargetAsset)
	if l > 0 {
		n += 1 + l + sovTypeTxOut(uint64(l))
	}
	if m.AggregatorTargetLimit != nil {
		l = m.AggregatorTargetLimit.Size()
		n += 1 + l + sovTypeTxOut(uint64(l))
	}
	return n
}

func (m *TxOut) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovTypeTxOut(uint64(m.Height))
	}
	if len(m.TxArray) > 0 {
		for _, e := range m.TxArray {
			l = e.Size()
			n += 1 + l + sovTypeTxOut(uint64(l))
		}
	}
	return n
}

func sovTypeTxOut(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypeTxOut(x uint64) (n int) {
	return sovTypeTxOut(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *TxOut) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForTxArray := "[]TxOutItem{"
	for _, f := range this.TxArray {
		repeatedStringForTxArray += fmt.Sprintf("%v", f) + ","
	}
	repeatedStringForTxArray += "}"
	s := strings.Join([]string{`&TxOut{`,
		`Height:` + fmt.Sprintf("%v", this.Height) + `,`,
		`TxArray:` + repeatedStringForTxArray + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringTypeTxOut(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *TxOutItem) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypeTxOut
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TxOutItem: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TxOutItem: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Chain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeTxOut
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypeTxOut
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeTxOut
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Chain = gitlab_com_mayachain_mayanode_common.Chain(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeTxOut
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypeTxOut
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeTxOut
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ToAddress = gitlab_com_mayachain_mayanode_common.Address(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VaultPubKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeTxOut
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypeTxOut
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeTxOut
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VaultPubKey = gitlab_com_mayachain_mayanode_common.PubKey(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coin", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeTxOut
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypeTxOut
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypeTxOut
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Coin.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Memo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeTxOut
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypeTxOut
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeTxOut
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Memo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxGas", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeTxOut
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypeTxOut
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypeTxOut
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MaxGas = append(m.MaxGas, common.Coin{})
			if err := m.MaxGas[len(m.MaxGas)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasRate", wireType)
			}
			m.GasRate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeTxOut
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GasRate |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeTxOut
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypeTxOut
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeTxOut
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InHash = gitlab_com_mayachain_mayanode_common.TxID(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeTxOut
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypeTxOut
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeTxOut
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OutHash = gitlab_com_mayachain_mayanode_common.TxID(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModuleName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeTxOut
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypeTxOut
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeTxOut
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModuleName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Aggregator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeTxOut
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypeTxOut
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeTxOut
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Aggregator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AggregatorTargetAsset", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeTxOut
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypeTxOut
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeTxOut
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AggregatorTargetAsset = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AggregatorTargetLimit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeTxOut
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypeTxOut
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeTxOut
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_cosmos_cosmos_sdk_types.Uint
			m.AggregatorTargetLimit = &v
			if err := m.AggregatorTargetLimit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypeTxOut(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTypeTxOut
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTypeTxOut
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TxOut) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypeTxOut
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TxOut: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TxOut: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeTxOut
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxArray", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeTxOut
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypeTxOut
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypeTxOut
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxArray = append(m.TxArray, TxOutItem{})
			if err := m.TxArray[len(m.TxArray)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypeTxOut(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTypeTxOut
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTypeTxOut
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypeTxOut(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypeTxOut
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypeTxOut
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypeTxOut
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypeTxOut
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypeTxOut
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypeTxOut
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypeTxOut        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypeTxOut          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypeTxOut = fmt.Errorf("proto: unexpected end of group")
)
