// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mayachain/v1/x/mayachain/types/type_network.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Network struct {
	BondRewardRune           github_com_cosmos_cosmos_sdk_types.Uint `protobuf:"bytes,1,opt,name=bond_reward_rune,json=bondRewardRune,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Uint" json:"bond_reward_rune"`
	TotalBondUnits           github_com_cosmos_cosmos_sdk_types.Uint `protobuf:"bytes,2,opt,name=total_bond_units,json=totalBondUnits,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Uint" json:"total_bond_units"`
	LPIncomeSplit            int64                                   `protobuf:"varint,3,opt,name=LPIncomeSplit,proto3" json:"LPIncomeSplit,omitempty"`
	NodeIncomeSplit          int64                                   `protobuf:"varint,4,opt,name=NodeIncomeSplit,proto3" json:"NodeIncomeSplit,omitempty"`
	OutboundGasSpentCacao    uint64                                  `protobuf:"varint,5,opt,name=outbound_gas_spent_cacao,json=outboundGasSpentCacao,proto3" json:"outbound_gas_spent_cacao,omitempty"`
	OutboundGasWithheldCacao uint64                                  `protobuf:"varint,6,opt,name=outbound_gas_withheld_cacao,json=outboundGasWithheldCacao,proto3" json:"outbound_gas_withheld_cacao,omitempty"`
}

func (m *Network) Reset()         { *m = Network{} }
func (m *Network) String() string { return proto.CompactTextString(m) }
func (*Network) ProtoMessage()    {}
func (*Network) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c05f8ccf9f3d0a6, []int{0}
}
func (m *Network) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Network) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Network.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Network) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Network.Merge(m, src)
}
func (m *Network) XXX_Size() int {
	return m.Size()
}
func (m *Network) XXX_DiscardUnknown() {
	xxx_messageInfo_Network.DiscardUnknown(m)
}

var xxx_messageInfo_Network proto.InternalMessageInfo

func (m *Network) GetLPIncomeSplit() int64 {
	if m != nil {
		return m.LPIncomeSplit
	}
	return 0
}

func (m *Network) GetNodeIncomeSplit() int64 {
	if m != nil {
		return m.NodeIncomeSplit
	}
	return 0
}

func (m *Network) GetOutboundGasSpentCacao() uint64 {
	if m != nil {
		return m.OutboundGasSpentCacao
	}
	return 0
}

func (m *Network) GetOutboundGasWithheldCacao() uint64 {
	if m != nil {
		return m.OutboundGasWithheldCacao
	}
	return 0
}

func init() {
	proto.RegisterType((*Network)(nil), "types.Network")
}

func init() {
	proto.RegisterFile("mayachain/v1/x/mayachain/types/type_network.proto", fileDescriptor_4c05f8ccf9f3d0a6)
}

var fileDescriptor_4c05f8ccf9f3d0a6 = []byte{
	// 358 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xcf, 0x4a, 0xeb, 0x40,
	0x14, 0xc6, 0x93, 0xdb, 0x3f, 0x97, 0x1b, 0xb8, 0xf7, 0x4a, 0x50, 0x08, 0x0a, 0x69, 0x11, 0xc1,
	0x6c, 0x6c, 0x28, 0x2e, 0x5c, 0xb9, 0xa9, 0x0b, 0x29, 0x48, 0x91, 0x94, 0x22, 0xba, 0x19, 0x26,
	0x99, 0x21, 0x19, 0x9a, 0xcc, 0x09, 0x99, 0x89, 0xb5, 0x4f, 0xe0, 0xd6, 0xc7, 0xea, 0xb2, 0x4b,
	0x71, 0x51, 0xa4, 0x7d, 0x11, 0x99, 0x49, 0xa5, 0xad, 0xee, 0xdc, 0x24, 0x67, 0xce, 0xf7, 0x7d,
	0xbf, 0x19, 0xe6, 0x8c, 0xd5, 0xcd, 0xf0, 0x14, 0x47, 0x09, 0x66, 0xdc, 0x7f, 0xec, 0xfa, 0x4f,
	0xfe, 0x66, 0x29, 0xa7, 0x39, 0x15, 0xfa, 0x8b, 0x38, 0x95, 0x13, 0x28, 0xc6, 0x9d, 0xbc, 0x00,
	0x09, 0x76, 0x43, 0x2b, 0x87, 0xfb, 0x31, 0xc4, 0xa0, 0x3b, 0xbe, 0xaa, 0x2a, 0xf1, 0xf8, 0xb9,
	0x66, 0xfd, 0x1e, 0x54, 0x76, 0xfb, 0xde, 0xda, 0x0b, 0x81, 0x13, 0x54, 0xd0, 0x09, 0x2e, 0x08,
	0x2a, 0x4a, 0x4e, 0x1d, 0xb3, 0x6d, 0x7a, 0x7f, 0x7a, 0xfe, 0x6c, 0xd1, 0x32, 0xde, 0x16, 0xad,
	0xd3, 0x98, 0xc9, 0xa4, 0x0c, 0x3b, 0x11, 0x64, 0x7e, 0x04, 0x22, 0x03, 0xb1, 0xfe, 0x9d, 0x09,
	0x32, 0xae, 0x4e, 0xd0, 0x19, 0x31, 0x2e, 0x83, 0x7f, 0x0a, 0x14, 0x68, 0x4e, 0x50, 0x72, 0xaa,
	0xd0, 0x12, 0x24, 0x4e, 0x91, 0xde, 0xa0, 0xe4, 0x4c, 0x0a, 0xe7, 0xd7, 0x0f, 0xd1, 0x1a, 0xd4,
	0x03, 0x4e, 0x46, 0x0a, 0x63, 0x9f, 0x58, 0x7f, 0x6f, 0x6e, 0xfb, 0x3c, 0x82, 0x8c, 0x0e, 0xf3,
	0x94, 0x49, 0xa7, 0xd6, 0x36, 0xbd, 0x5a, 0xb0, 0xdb, 0xb4, 0x3d, 0xeb, 0xff, 0x00, 0x08, 0xdd,
	0xf6, 0xd5, 0xb5, 0xef, 0x6b, 0xdb, 0xbe, 0xb0, 0x1c, 0x28, 0x65, 0x08, 0x25, 0x27, 0x28, 0xc6,
	0x02, 0x89, 0x9c, 0x72, 0x89, 0x22, 0x1c, 0x61, 0x70, 0x1a, 0x6d, 0xd3, 0xab, 0x07, 0x07, 0x9f,
	0xfa, 0x35, 0x16, 0x43, 0xa5, 0x5e, 0x29, 0xd1, 0xbe, 0xb4, 0x8e, 0x76, 0x82, 0x13, 0x26, 0x93,
	0x84, 0xa6, 0x64, 0x9d, 0x6d, 0xea, 0xac, 0xb3, 0x95, 0xbd, 0x5b, 0x1b, 0x74, 0xbc, 0xd7, 0x9f,
	0x2d, 0x5d, 0x73, 0xbe, 0x74, 0xcd, 0xf7, 0xa5, 0x6b, 0xbe, 0xac, 0x5c, 0x63, 0xbe, 0x72, 0x8d,
	0xd7, 0x95, 0x6b, 0x3c, 0xf8, 0x31, 0x93, 0x29, 0xae, 0xae, 0x66, 0x33, 0x6f, 0x55, 0x71, 0x20,
	0xf4, 0xfb, 0x23, 0x08, 0x9b, 0x7a, 0xb6, 0xe7, 0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2c, 0xca,
	0x18, 0x33, 0x2d, 0x02, 0x00, 0x00,
}

func (m *Network) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Network) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Network) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.OutboundGasWithheldCacao != 0 {
		i = encodeVarintTypeNetwork(dAtA, i, uint64(m.OutboundGasWithheldCacao))
		i--
		dAtA[i] = 0x30
	}
	if m.OutboundGasSpentCacao != 0 {
		i = encodeVarintTypeNetwork(dAtA, i, uint64(m.OutboundGasSpentCacao))
		i--
		dAtA[i] = 0x28
	}
	if m.NodeIncomeSplit != 0 {
		i = encodeVarintTypeNetwork(dAtA, i, uint64(m.NodeIncomeSplit))
		i--
		dAtA[i] = 0x20
	}
	if m.LPIncomeSplit != 0 {
		i = encodeVarintTypeNetwork(dAtA, i, uint64(m.LPIncomeSplit))
		i--
		dAtA[i] = 0x18
	}
	{
		size := m.TotalBondUnits.Size()
		i -= size
		if _, err := m.TotalBondUnits.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTypeNetwork(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.BondRewardRune.Size()
		i -= size
		if _, err := m.BondRewardRune.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTypeNetwork(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintTypeNetwork(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypeNetwork(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Network) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.BondRewardRune.Size()
	n += 1 + l + sovTypeNetwork(uint64(l))
	l = m.TotalBondUnits.Size()
	n += 1 + l + sovTypeNetwork(uint64(l))
	if m.LPIncomeSplit != 0 {
		n += 1 + sovTypeNetwork(uint64(m.LPIncomeSplit))
	}
	if m.NodeIncomeSplit != 0 {
		n += 1 + sovTypeNetwork(uint64(m.NodeIncomeSplit))
	}
	if m.OutboundGasSpentCacao != 0 {
		n += 1 + sovTypeNetwork(uint64(m.OutboundGasSpentCacao))
	}
	if m.OutboundGasWithheldCacao != 0 {
		n += 1 + sovTypeNetwork(uint64(m.OutboundGasWithheldCacao))
	}
	return n
}

func sovTypeNetwork(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypeNetwork(x uint64) (n int) {
	return sovTypeNetwork(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Network) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypeNetwork
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Network: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Network: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondRewardRune", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeNetwork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypeNetwork
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeNetwork
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BondRewardRune.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalBondUnits", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeNetwork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypeNetwork
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeNetwork
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalBondUnits.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LPIncomeSplit", wireType)
			}
			m.LPIncomeSplit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeNetwork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LPIncomeSplit |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeIncomeSplit", wireType)
			}
			m.NodeIncomeSplit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeNetwork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NodeIncomeSplit |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutboundGasSpentCacao", wireType)
			}
			m.OutboundGasSpentCacao = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeNetwork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OutboundGasSpentCacao |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutboundGasWithheldCacao", wireType)
			}
			m.OutboundGasWithheldCacao = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeNetwork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OutboundGasWithheldCacao |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypeNetwork(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTypeNetwork
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTypeNetwork
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypeNetwork(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypeNetwork
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypeNetwork
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypeNetwork
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypeNetwork
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypeNetwork
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypeNetwork
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypeNetwork        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypeNetwork          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypeNetwork = fmt.Errorf("proto: unexpected end of group")
)
