// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mayachain/v1/x/mayachain/types/type_liquidity_auction_tier.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	gitlab_com_mayachain_mayanode_common "gitlab.com/mayachain/mayanode/common"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type LiquidityAuctionTier struct {
	Address gitlab_com_mayachain_mayanode_common.Address `protobuf:"bytes,1,opt,name=address,proto3,casttype=gitlab.com/mayachain/mayanode/common.Address" json:"address,omitempty"`
	Tier    int64                                        `protobuf:"varint,2,opt,name=tier,proto3" json:"tier,omitempty"`
}

func (m *LiquidityAuctionTier) Reset()         { *m = LiquidityAuctionTier{} }
func (m *LiquidityAuctionTier) String() string { return proto.CompactTextString(m) }
func (*LiquidityAuctionTier) ProtoMessage()    {}
func (*LiquidityAuctionTier) Descriptor() ([]byte, []int) {
	return fileDescriptor_cea03089d05bf3ce, []int{0}
}
func (m *LiquidityAuctionTier) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LiquidityAuctionTier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LiquidityAuctionTier.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LiquidityAuctionTier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiquidityAuctionTier.Merge(m, src)
}
func (m *LiquidityAuctionTier) XXX_Size() int {
	return m.Size()
}
func (m *LiquidityAuctionTier) XXX_DiscardUnknown() {
	xxx_messageInfo_LiquidityAuctionTier.DiscardUnknown(m)
}

var xxx_messageInfo_LiquidityAuctionTier proto.InternalMessageInfo

func (m *LiquidityAuctionTier) GetAddress() gitlab_com_mayachain_mayanode_common.Address {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *LiquidityAuctionTier) GetTier() int64 {
	if m != nil {
		return m.Tier
	}
	return 0
}

func init() {
	proto.RegisterType((*LiquidityAuctionTier)(nil), "types.LiquidityAuctionTier")
}

func init() {
	proto.RegisterFile("mayachain/v1/x/mayachain/types/type_liquidity_auction_tier.proto", fileDescriptor_cea03089d05bf3ce)
}

var fileDescriptor_cea03089d05bf3ce = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x72, 0xc8, 0x4d, 0xac, 0x4c,
	0x4c, 0xce, 0x48, 0xcc, 0xcc, 0xd3, 0x2f, 0x33, 0xd4, 0xaf, 0xd0, 0x47, 0x70, 0x4b, 0x2a, 0x0b,
	0x52, 0x8b, 0xc1, 0x64, 0x7c, 0x4e, 0x66, 0x61, 0x69, 0x66, 0x4a, 0x66, 0x49, 0x65, 0x7c, 0x62,
	0x69, 0x72, 0x49, 0x66, 0x7e, 0x5e, 0x7c, 0x49, 0x66, 0x6a, 0x91, 0x5e, 0x41, 0x51, 0x7e, 0x49,
	0xbe, 0x10, 0x2b, 0x58, 0xa1, 0x94, 0x48, 0x7a, 0x7e, 0x7a, 0x3e, 0x58, 0x44, 0x1f, 0xc4, 0x82,
	0x48, 0x2a, 0x95, 0x71, 0x89, 0xf8, 0xc0, 0x34, 0x3b, 0x42, 0xf4, 0x86, 0x64, 0xa6, 0x16, 0x09,
	0x79, 0x71, 0xb1, 0x27, 0xa6, 0xa4, 0x14, 0xa5, 0x16, 0x17, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0x70,
	0x3a, 0x19, 0xfc, 0xba, 0x27, 0xaf, 0x93, 0x9e, 0x59, 0x92, 0x93, 0x98, 0xa4, 0x97, 0x9c, 0x9f,
	0x8b, 0xe4, 0x0e, 0x10, 0x2b, 0x2f, 0x3f, 0x25, 0x55, 0x3f, 0x39, 0x3f, 0x37, 0x37, 0x3f, 0x4f,
	0xcf, 0x11, 0xa2, 0x2f, 0x08, 0x66, 0x80, 0x90, 0x10, 0x17, 0x0b, 0xc8, 0x39, 0x12, 0x4c, 0x0a,
	0x8c, 0x1a, 0xcc, 0x41, 0x60, 0xb6, 0x93, 0xe7, 0x89, 0x47, 0x72, 0x8c, 0x17, 0x1e, 0xc9, 0x31,
	0x3e, 0x78, 0x24, 0xc7, 0x38, 0xe1, 0xb1, 0x1c, 0xc3, 0x85, 0xc7, 0x72, 0x0c, 0x37, 0x1e, 0xcb,
	0x31, 0x44, 0xe9, 0xe3, 0xb7, 0x04, 0x23, 0x04, 0x92, 0xd8, 0xc0, 0x3e, 0x31, 0x06, 0x04, 0x00,
	0x00, 0xff, 0xff, 0xb1, 0x6a, 0x0e, 0x9a, 0x2a, 0x01, 0x00, 0x00,
}

func (m *LiquidityAuctionTier) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LiquidityAuctionTier) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LiquidityAuctionTier) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Tier != 0 {
		i = encodeVarintTypeLiquidityAuctionTier(dAtA, i, uint64(m.Tier))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTypeLiquidityAuctionTier(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypeLiquidityAuctionTier(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypeLiquidityAuctionTier(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *LiquidityAuctionTier) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTypeLiquidityAuctionTier(uint64(l))
	}
	if m.Tier != 0 {
		n += 1 + sovTypeLiquidityAuctionTier(uint64(m.Tier))
	}
	return n
}

func sovTypeLiquidityAuctionTier(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypeLiquidityAuctionTier(x uint64) (n int) {
	return sovTypeLiquidityAuctionTier(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *LiquidityAuctionTier) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypeLiquidityAuctionTier
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LiquidityAuctionTier: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LiquidityAuctionTier: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeLiquidityAuctionTier
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypeLiquidityAuctionTier
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeLiquidityAuctionTier
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = gitlab_com_mayachain_mayanode_common.Address(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tier", wireType)
			}
			m.Tier = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeLiquidityAuctionTier
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Tier |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypeLiquidityAuctionTier(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTypeLiquidityAuctionTier
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTypeLiquidityAuctionTier
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypeLiquidityAuctionTier(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypeLiquidityAuctionTier
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypeLiquidityAuctionTier
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypeLiquidityAuctionTier
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypeLiquidityAuctionTier
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypeLiquidityAuctionTier
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypeLiquidityAuctionTier
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypeLiquidityAuctionTier        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypeLiquidityAuctionTier          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypeLiquidityAuctionTier = fmt.Errorf("proto: unexpected end of group")
)
